main_app/urls.py
from django.urls import path, include
from .views import (
    list_function,
    add_todo,
    detail_todo,
    edit_todo,
    delete_list,
    archives_list,
    archive_todo,
    done_todo,
    done_todo_list,
    search_todo,
    starred_todo,
    starred_todo_list
)

app_name = 'main_app'

urlpatterns = [
    path('', list_function, name='home'),
    path('create/', add_todo, name='create'),
    path('done/', done_todo, name='done'),  
    path('search/', search_todo, name='search'),
    path('<int:pk>', detail_todo, name='detail'),
    path('<int:pk>/edit', edit_todo, name='edit'),
    path('<int:pk>/delete', delete_list, name='delete'),
    path('archive', archive_todo, name='archive'),
    path('archives', archives_list, name='archive-list'),
    path('completed', done_todo_list, name='completed-list'),
    
    path('starred', starred_todo_list, name='starred-list'),
    path('star', starred_todo, name='star'),
]

tags/urls.py
from django.urls import path, include
from .views import (
    tag_list,
    add_tag,
    edit_tag, 
    delete_tag
)

app_name = 'tag'

urlpatterns = [
    path('', tag_list, name='list'),
    path('create/', add_tag, name='create'),
    path('<int:pk>/edit', edit_tag, name='edit'),
    path('<int:pk>/delete', delete_tag, name='delete'),

]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main_app.urls'), name='list'),
    path('tag/', include('tags.urls'), name='tag'),
    path('accounts/', include('allauth.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

main_app/models.py
from django.db import models
from django.shortcuts import redirect, reverse
from django.utils import timezone

from django.contrib.auth.models import User
import tags.models

# Create your models here.
class ToDoModel(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	text = models.CharField(max_length=120)
	description = models.TextField(blank=True, null=True)
	start_date = models.DateField(auto_now_add=True, null=True, blank=True)
	start_time = models.TimeField(auto_now_add=True, null=True, blank=True)
	end_date = models.DateField(default=timezone.now, null=True, blank=True)
	end_time = models.TimeField(null=True, blank=True)
	done = models.BooleanField(default=False)
	archive = models.BooleanField(default=False)
	tags = models.ManyToManyField('tags.Tag', blank=True)
	starred = models.BooleanField(default=False)

	class Meta():
		ordering = [ '-id' ]
 
	def __str__(self):
		return self.text

	def get_absolute_url(self):
		return reverse("main_app:detail", kwargs={"pk": self.pk})


class ImageTodo(models.Model):
    todo = models.ForeignKey(ToDoModel, on_delete=models.CASCADE)
    image = models.FileField(upload_to='user/media')
    
    def __str__(self):
	    return self.todo.text
    


	

main_app/forms.py
from django import forms
from .widgets import TimePickerInput


from tags.models import Tag
from .models import *

class TodoModelForm(forms.ModelForm):
	end_date =forms.DateField(widget = forms.SelectDateWidget(), required=False)
	end_time = forms.TimeField(widget=TimePickerInput, required=False)
	class Meta:
		model = ToDoModel
		fields = ['text', 'description', 'end_date', 'end_time', 'tags']

	def __init__(self, *args,**kwargs):
		user_set = kwargs.pop('user_set', None)
		super(TodoModelForm, self).__init__(*args,**kwargs)
		self.fields['tags'].queryset = Tag.objects.filter(user=user_set)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

main_app/api/views.py
from rest_framework.response import Response
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.views import APIView
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAdminUser, IsAuthenticated


from .serializer import ToDoSerializer
from ..models import ToDoModel, ImageTodo


class ListCreateToDoAPI(APIView):
    permission_classes = [IsAuthenticated,]
    queryset = ToDoModel.objects.all()
    
    def get(request):
        return Response()
    

main_app/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .forms import TodoModelForm
from .models import ToDoModel
from tags.models import Tag
from tags.forms import TagForm



# Create your views here.
def list_function(request):
    user = get_user_set(request)
    if user.is_authenticated:
        cat = None
        try:
            cat = Tag.objects.filter(user=user)
        except:
            print('e')
        objects_list = ToDoModel.objects.filter(done=False).filter(archive=False).filter(user=user)
        context = {}
        if objects_list.exists():
            context = {
                'objects_list':objects_list,
                'categories': cat,
            }
    else:
        context = {}
        
    return render(request, 'main_app/home.html', context)

@login_required(login_url='account_login')
def add_todo(request):
    user = get_user_set(request)
    todo_form = TodoModelForm(request.POST, user_set=user)
    tag_form = TagForm(request.POST or None)
    context = {}
    context['form'] = todo_form
    if request.POST:
        if todo_form.is_valid():
            instance = todo_form.save(commit=False)
            instance.user = user
            instance.save()
            context['form'] = todo_form
            return redirect('main_app:home')
        if tag_form.is_valid():
            instance = tag_form.save()
            return redirect('main_app:create')
    return render(request, "main_app/add_todo.html", context=context)


@login_required(login_url='account_login')  
def detail_todo(request, pk=None):
    context = {}
    user = request.user
    if user.is_authenticated:
        obj = get_object_or_404(ToDoModel, pk=pk)
        if obj.user == user:
            if obj is not None:
                context = {
                    'object':obj
                } 
        
    return render(request, 'main_app/detail_todo.html', context=context)
    
    
@login_required(login_url='account_login')        
def edit_todo(request, pk=None):
    instance = get_object_or_404(ToDoModel, pk=pk)
    user = get_user_set(request)
    todo_form = TodoModelForm(request.POST or None, instance=instance, user_set=user)
    context = {}
    context['form'] = todo_form

    if request.POST:
        if todo_form.is_valid():
            instance = todo_form.save(commit=False)
            instance.user = user
            try:
                tag = Tag.objects.prefetch_related(tag__in=request.POST.get('tags'))
                instance.tags.set(tag)
            except:
                pass
            todo_form.save_m2m()
            instance.save()
            return redirect('main_app:home')
    
    return render(request, "main_app/add_todo.html", context=context)   

@login_required(login_url='account_login')
def detail_todo(request, pk=None):
	obj = ToDoModel.objects.filter(pk=pk).filter(user=request.user)
	context = {
		'object':obj
	}
	return render(request, 'main_app/detail_todo.html', context)

@login_required(login_url='account_login')
def delete_list(request, pk=None):
	obj = ToDoModel.objects.filter(pk=pk).filter(user=request.user)
	obj.delete()
	
	return render(request, 'main_app/home.html', {})

@login_required(login_url='account_login')
def done_todo(request):
    if request.POST:
        pk = request.POST.get('pk')
        user = request.user
        if pk is not None:
            obj = get_object_or_404(ToDoModel, pk=pk, user=user)
            if obj.done == True:
                obj.done=False
            else:
                obj.done=True
            obj.save()
            request.session['completed_count'] = ToDoModel.objects.filter(done=True).filter(user=user).count()
            return redirect('main_app:home')
    return render(request, "main_app/home.html", context={})

@login_required(login_url='account_login')
def archives_list(request):
    objects_list = ToDoModel.objects.filter(archive=True).filter(user=request.user)
    context = {
		'objects_list':objects_list
	}
    return render(request, 'main_app/home.html', context=context)

@login_required(login_url='account_login')
def archive_todo(request):
    if request.POST:
        pk = request.POST.get('pk')
        user = request.user
        if pk is not None:
            obj = get_object_or_404(ToDoModel, pk=pk, user=user)
            if obj.archive == True:
                obj.archive=False
            else:
                obj.archive=True
            obj.save()
            request.session['archive_count'] = ToDoModel.objects.filter(archive=True).filter(user=user).count()
            return redirect('main_app:home')
    return render(request, "main_app/home.html", context={})

@login_required(login_url='account_login')
def search_todo(request):
    context = {}
    qs = None
    user = get_user_set(request)
    try:
        cat = Tag.objects.filter(user=user)
        context['categories'] = cat
    except:
        pass
    
    if user.is_authenticated:
        query = request.GET.get('q')
        cat = request.GET.get('category')
        
        if query is not None and cat is None:
            qs = ToDoModel.objects.filter(
                Q(text__icontains=query) |
                Q(start_date__icontains=query) |
                Q(end_date__icontains=query) |
                Q(tags__tag__icontains=query)
            ).filter(user=user)
        
        elif query is None and cat is not None:
            qs = ToDoModel.objects.filter(
               Q(tags__tag__icontains=cat)
            ).filter(user=user)
            
        elif query is not None and cat is not None:
            qs = ToDoModel.objects.filter(
                Q(text__icontains=query) |
                Q(start_date__icontains=query) |
                Q(end_date__icontains=query) |
                Q(tags__tag__icontains=query)
            ).filter(user=user).filter(Q(tags__tag__icontains=query))
        
        if qs is not None:
            context['objects_list'] = qs
            
    else:
        context = {}
        
    return render(request, 'main_app/home.html', context)

@login_required(login_url='account_login')
def done_todo_list(request):
    objects_list = ToDoModel.objects.filter(done=True).filter(user=request.user)
    context = {
		'objects_list':objects_list
	}
    return render(request, 'main_app/home.html', context)


@login_required(login_url='account_login')
def starred_todo(request):
    if request.POST:
        pk = request.POST.get('pk')
        user = request.user
        if pk is not None:
            obj = get_object_or_404(ToDoModel, pk=pk, user=user)
            if obj.starred == True:
                obj.starred=False
            else:
                obj.starred=True
            obj.save()
            request.session['starred_count'] = ToDoModel.objects.filter(starred=True).filter(user=user).count()
            return redirect('main_app:home')
    return render(request, "main_app/home.html", context={})


@login_required(login_url='account_login')
def starred_todo_list(request):
    objects_list = ToDoModel.objects.filter(starred=True).filter(user=request.user)
    context = {
		'objects_list':objects_list
	}
    return render(request, 'main_app/home.html', context)


def get_user_set(request):
    user = request.user
    return user

templates/main_app/add_todo.html
{% extends 'main_app/base.html' %}
{% block body_block %}

<div class='container-sm'>
<br>
<br>


<form method='POST'>
    {% csrf_token %} 
    {{ form.as_p }}
    <input type='submit' value='submit' name='add' class='btn btn-outline-dark'>
    
    <br>
<br>
</form>

<form class='tags' method='GET' action='{% url "tag:create" %}'>
    <input type='hidden' name='next' value="{{ request.path }}">
    <input type="submit" class="btn btn-outline-warning" name='Add Tag' value='Add Tag'>
</form>


<hr>
</div>




{% endblock %}

templates/main_app/base.html
{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <style>
    .no-blue {
      text-decaration: none;
      color:#FF ;
    }

    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: black;
        color: white;
        text-align: center;
    }
    
    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>To-Do App</title>
  </head>
  <body>
    {% include 'snippets/navbar.html' %}
    <div class='container-fluid'>
{% block body_block %}

{% endblock %}
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  
    <script type="text/javascript" src="/my_admin/jsi18n/"></script>
    <script type="text/javascript" src="/media/admin/js/core.js"></script>

  <footer class="footer text-center">
        <div class="container">
            <small class="copyright">Copyright @ <a href="https://stormy-hamlet-70851.herokuapp.com/">Thakkar Parth </a></small>
        </div><!--//container-->
    </footer>
  
  </body>


</html>

templates/main_app/detail_todo.html
{% extends 'main_app/base.html' %}

{% block body_block %}
<br></br>

{% if object %}

{% for object in object %}
<center>

<h1> {{ object.text }} </h1>
</br>
<hr>

<center>
{% for tag in object.tags.all %}
<span class="badge badge-pill badge-success">{{ tag.tag }}</span> 
{% endfor %} 
</center>

<br>
<br>
<p>

{{ object.description }}
</p>


<hr>
<br>
<a href="{% url 'main_app:edit' pk=object.pk %}">
<button type="button" class="btn btn-outline-warning">Edit</button></a>
 <a href='{% url "main_app:delete" pk=object.pk %}'><button type="button" class="btn btn-outline-danger">Delete</button><a>
 &emsp;


<form method='POST' style="float: right" action='{% url "main_app:archive" %}'>
 {% csrf_token %}
 <input type='hidden' value="{{ object.pk }}" name='pk'>
 {% if not object.archive %}
   <input type='submit' value='Archive' name='Archive'>
  {% else %}
  <input type='submit' value='Un-archive' name='Unarchive'>
{% endif %}
</form> 

<form method='POST' style="float: right" action='{% url "main_app:star" %}'>
 {% csrf_token %}
 <input type='hidden' value="{{ object.pk }}" name='pk'>
 {% if not object.starred %}
   <input type='submit' value='Star' name='Star'>
  {% else %}
  <input type='submit' value='Un-Star' name='Un-Star'>
{% endif %}
</form> 


<form method='POST' style="float: right" action='{% url "main_app:done" %}'>
 {% csrf_token %}
 <input type='hidden' value="{{ object.pk }}" name='pk'>
 {% if not object.done %}
   <input type='submit' value='Done' name='Done'>
  {% else %}
  <input type='submit' value='undone' name='undone'>
{% endif %}
</form>


&emsp;
<div class='container-fluid'>
<br>
Created on : {{ object.start_date }} - {{ object.start_time}}
<br>{% if object.end_date %}
End Date: {{ object.end_date }} {% else %}{% endif %}
{% if object.end_time %}
End Time: {{ object.end_time }}{% else %}{% endif %}
</div>
</br>
</hr>
<br>

{% endfor %}
{% endif %}

</center>
{% endblock %}

templates/main_app/home.html
{% extends 'main_app/base.html' %}

{% block body_block %}
<style>
.button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 5px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 2px 1px;
  cursor: pointer;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}
</style>


<br></br>

{% url 'main_app:home' as home_url %}

<div class='container-sm'>
  <form method='get' action="{% url 'main_app:search' %}">

        <div class="input-group md-3">
          <select id="category" class="form-control" name="category" style="margin:10px">
            <option selected>Select Categories...</option>
            {% for cat in categories %}
            <option value="{{ cat }}">{{ cat }}</option>
            {% endfor %}
          </select>
            <div class="input-group-prepend"> 
            <input class='button' style="float: " type='submit' name='submit' class='btn btn-primary form-control-sm center'>
            </div>
        </div>
  </form>
  </div>

{% if request.path == home_url %}
<a href='{% url "main_app:create" %}'><button type="button" class="btn btn-success btn-lg btn-block">Add Note</button></a></br></hr>
<br>
{% else %}
{% endif %}



{% if objects_list %}
<div class='container-sm'>
<ul class="list-group">

{% for obj in objects_list %}<center>
&emsp; &emsp; <li class="list-group-item">
              <a class='no-blue' href="{{ obj.get_absolute_url }}">{{ obj }}</a> &emsp; 


  {% for tag in obj.tags.all %}
  <span class="badge badge-pill badge-success">{{ tag.tag }}</span> 
  {% endfor %} 


    <form method='POST' style="float: right" action='{% url "main_app:archive" %}'>
      {% csrf_token %}
      <input type='hidden' value="{{ obj.pk }}" name='pk'>
      {% if not obj.archive %}
        <input type='submit' value='Archive' name='Archive' class='btn btn-outline-dark'>
        {% else %}
        <input type='submit' value='Un-archive' name='Unarchive' class='btn btn-outline-dark'>
      {% endif %}
    </form> 

    | &emsp;
    <a href='{% url "main_app:edit" pk=obj.pk %}'>
    <button type="button" class="btn btn-outline-warning">Edit</button></a>
    <a href='{% url "main_app:delete" pk=obj.pk %}'><button type="button" class="btn btn-outline-danger">Delete</button><a>
    &emsp;

    <form method='POST' style="float: right" action='{% url "main_app:done" %}'>
      {% csrf_token %}
      <input type='hidden' value="{{ obj.pk }}" name='pk'>
        {% if not obj.done %}
          <input type='submit' value='Done' name='Done' class='btn btn-outline-dark'>
        {% else %}
          <input type='submit' value='undone' name='undone' class='btn btn-outline-dark'>
        {% endif %}
    </form>

    &emsp;


</li>
{% endfor %}
</ul>

</div>
{% endif %}
</center>
{% endblock %}