main_app/urls.py
from django.urls import path, include
from .views import (
    list_function,
    add_todo,
    detail_todo,
    edit_todo,
    delete_list,
    archives_list,
    archive_todo,
    done_todo,
    done_todo_list,
    search_todo,
    starred_todo,
    starred_todo_list
)

app_name = 'main_app'

urlpatterns = [
    path('', list_function, name='home'),
    path('create/', add_todo, name='create'),
    path('done/', done_todo, name='done'),  
    path('search/', search_todo, name='search'),
    path('<int:pk>', detail_todo, name='detail'),
    path('<int:pk>/edit', edit_todo, name='edit'),
    path('<int:pk>/delete', delete_list, name='delete'),
    path('archive', archive_todo, name='archive'),
    path('archives', archives_list, name='archive-list'),
    path('completed', done_todo_list, name='completed-list'),
    
    path('starred', starred_todo_list, name='starred-list'),
    path('star', starred_todo, name='star'),
]

tags/urls.py
from django.urls import path, include
from .views import (
    tag_list,
    add_tag,
    edit_tag, 
    delete_tag
)

app_name = 'tag'

urlpatterns = [
    path('', tag_list, name='list'),
    path('create/', add_tag, name='create'),
    path('<int:pk>/edit', edit_tag, name='edit'),
    path('<int:pk>/delete', delete_tag, name='delete'),

]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main_app.urls'), name='list'),
    path('tag/', include('tags.urls'), name='tag'),
    path('accounts/', include('allauth.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

templates/snippets/form.html
<form method='POST'>
 {% csrf_token %} 
 {{ form.as_p }}
 <input type='submit' value='submit' name='add'>
</form>

templates/snippets/navbar.html
{% load static %}

<nav class="navbar sticky-top fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'main_app:home' %}">
  <img src="{% static 'images/favicon.png' %%}" width="30" height="30" class="d-inline-block align-center" alt="">
   <span class="navbar-brand mb-0 h1">ToDo</span></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main_app:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main_app:archive-list' %}">Archives<span class="badge badge-light">{{ request.session.archive_count }}</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main_app:completed-list' %}">Completed<span class="badge badge-light">{{ request.session.completed_count }}</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main_app:starred-list' %}">Starred<span class="badge badge-light">{{ request.session.starred_count }}</span></a>
      </li>
      {% if request.user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main_app:starred-list' %}">Admin<span class="badge badge-light">{{ request.session.starred_count }}</span></a>
      </li>
      {% else %}{% endif %}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        {% if not request.user.is_authenticated %}
          <a class="dropdown-item" href="{% url 'account_login' %}">Login</a>
          <a class="dropdown-item" href="{% url 'account_signup' %}">Sign-Up</a>
          {% else %}
          <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
          {% endif %}
          
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'tag:list' %}">See Tags</a>
          <a class="dropdown-item" href="{% url 'tag:create' %}">Add Tag</a>
        </div>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0" method='GET' action='{% url "main_app:search" %}'>
      <input class="form-control" type="search" name='q' placeholder="Search" aria-label="Search" value='{{ request.GET.q }}'>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>